### ISSUE TITLE
Request for plugin: `poetry`

### ISSUE THREAD

**Issue by IgnisDa** [Phault/proto-toml-plugins#7]
Hi! Thanks for this repository. There is not information in the readme on how to request additional plugins.

Anyway, it would be great if there were a proto plugin for [poetry](https://python-poetry.org/docs/).

**Comment by Phault** [comment]
Hi!

First of, sorry for the late reply.

I wasn't really expecting requests, and don't really plan to put in the work myself for it, but you're welcome to create a PR similar to #8 and I'll gladly review and merge it.

`poetry` might be tricky to add, as it relies on python3 for the runtime and `pip` to install its dependencies. Proto TOML plugins are more suitable for self-contained executables.
